### ISSUE TITLE
[3] Избавиться от количества проверяемых элементов

### ISSUE THREAD

**Issue by jangot** [jangot/f-calculator#6]
В функции `get_value` используется цикл (проверка полей ввода). От него можно и нужно избавиться.
Этот цикл используется для того, что бы обойти все элементы `input` и забрать их значение. Для того, что бы это сделать лучше использовать функцию [`querySelectorAll`](https://developer.mozilla.org/ru/docs/Web/API/Document/querySelectorAll).

План действий:

1. Сформировать `CSS` селектор, для функции `querySelectorAll` так, что бы эта функция вернула все необходимые элементы (те которые сейчас обрабатываются в цикле).
2. Перед циклом создать переменную, к примеру `elementsList` и присвоить ей результат выполнения функции `querySelectorAll`.
3. Вместо "магического числа" 7 написать `elementsList.length` - в `length` хранится количество элементов в списке `elementsList`
4. Поменять начальное значение переменной `i` в цикле на 0.
5. Поменять присвоение значения переменной `in_i` из `elementsList[i]`.

**Comment by TimPulin** [comment]
избавился
