### ISSUE TITLE
[2] Убрать переменную `in_i` из глобального пространства

### ISSUE THREAD

**Issue by jangot** [jangot/f-calculator#7]
Сейчас переменная `in_i` определена так, что она используется в двух функциях `resett` (название этой функции стоит поправить) и в функции `get_value`.
Почему?
Глобальную переменную (такую переменную, которую видно из любой точки приложения) имеет смысл определять, когда необходимо сохранить какое-то состояние для всего приложения. Например, что кнопка была нажата и нужно проверять это в разных точках приложения (хотя это тоже плохая практика и так лучше не делать). В данном случае нет необходимости связывать эти две функции одной переменной, к тому же это может привести к ошибкам, так как значение переменной становиться не предсказуемым.
Можно оставить название переменной, изменив лишь место, в котором она создается (место создания переменной определяется ключевым словом `var`). В том месте, где она определена необходимо удалить, а написать `var in_i` в начале каждой функции где она используется.

В дополнение: Рекомендуется использовать более длинные и понятные имена переменных.

**Comment by TimPulin** [comment]
убрал. заодно убрал и переменную info
